### ISSUE TITLE
Hide 'Add Folder' and 'Add Bookmark' buttons when outside "edit" mode

### ISSUE THREAD

**Issue by bjagg** [Jasig/BookmarksPortlet#22]
Two "add" buttons are always visible; however, they only function when bookmark editing is allowed. They should be hidden when non-functional.

The UI really could use a refresh.

**Comment by cbeach47** [comment]
Bookmarks-Portlet-v1.2.2 has fixes up to and including ( https://github.com/Jasig/BookmarksPortlet/commit/b03b835bba67e74837c17727a4b7a36c86b50524 ), but the core of this issue still needs to be addressed (the add buttons are visible when not in `edit` mode).
