### ISSUE TITLE
Unable to delete bookmark

### ISSUE THREAD

**Issue by bjagg** [Jasig/BookmarksPortlet#24]
**Describe the bug**
When attempting to delete a bookmark, the user is greeted with the following message
>HTTP Status 405 - Request method 'GET' not supported

**To Reproduce**
1. Create a bookmark
2. Attempt to delete bookmark

**Expected behavior**
The bookmark being deleted

**Comment by bjagg** [comment]
Wrap line 169 for the delete action in baseAdmin.jsp with something like:

```
<form action="${portlet action link}" method="post">
<button type="submit">
<a href="javascript:void(0);">link text</a>
</button>
</form>
```

**Comment by cbeach47** [comment]
This has now been merged into `master` and will be available in the next release.
